[tool.pip-audit]
ignore-vulns = [
  "PYSEC-2022-20",
  "PYSEC-2022-19",
  "PYSEC-2022-190",
  "PYSEC-2022-191",
  "PYSEC-2022-213",
  "PYSEC-2022-245",
  "PYSEC-2022-304",
  "PYSEC-2023-13",
  "PYSEC-2023-12",
  "PYSEC-2023-61",
  "PYSEC-2023-100",
  "PYSEC-2023-222",
  "PYSEC-2023-225",
  "PYSEC-2023-226",
  "PYSEC-2024-28",
  "PYSEC-2024-47",
  "CVE-2024-45231",
  "CVE-2025-48432",
  "CVE-2025-57833",
  "CVE-2025-64458",
  "CVE-2025-64459",
  "CVE-2024-1135",
  "CVE-2024-6827",
  "CVE-2023-50447",
  "CVE-2024-28219"
]
