steps:
  - script: |
      wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
      tar -xvf gitleaks_8.18.0_linux_x64.tar.gz
      chmod +x gitleaks
      ./gitleaks detect -v --config=.gitleaks.toml
    displayName: "Credential Scanning"
