steps:
  - script: |
      python3 --version
      which python3
    displayName: "Verify Python"

  - script: |
      python3 -m venv $(Agent.ToolsDirectory)/venv
      source $(Agent.ToolsDirectory)/venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install Dependencies"

  - script: |
      source $(Agent.ToolsDirectory)/venv/bin/activate
      pip list
    displayName: "Verify installed packages"
